[features]
seeds = false
[programs.devnet]
mytestproject = "3oCttiW8UNdLnh5oJmoPZ37mW6srPL6HGx7QR4ANVyWv"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/Users/laoye_jnr/.config/solana/id.json"

[scripts]
test = "node tests/mytestproject.js"
